runtime: nodejs22

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /_next/static
  static_dir: .next/static
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=31536000, immutable'

- url: /.*
  script: auto
  secure: always
