#!/usr/bin/env bash
set -euo pipefail

IMAGE="europe-west1-docker.pkg.dev/serverless-tek89/cloud-run-source-deploy/frontend:manual"
REGION="europe-west1"
SERVICE="frontend"
PROJECT="${PROJECT:-serverless-tek89}"

echo "Building image with Dockerfile..."
gcloud builds submit --tag "$IMAGE" --project "$PROJECT" .

echo "Deploying to Cloud Run..."
gcloud run deploy "$SERVICE" \
  --region "$REGION" \
  --image "$IMAGE" \
  --allow-unauthenticated \
  --project "$PROJECT" \
  --set-secrets "NEXT_PUBLIC_API_URL=NEXT_PUBLIC_API_URL:latest,NEXT_PUBLIC_DISCORD_CLIENT_ID=NEXT_PUBLIC_DISCORD_CLIENT_ID:latest,NEXT_PUBLIC_DISCORD_REDIRECT_URI=NEXT_PUBLIC_DISCORD_REDIRECT_URI:latest,NEXT_PUBLIC_FIREBASE_API_KEY=NEXT_PUBLIC_FIREBASE_API_KEY:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:latest,NEXT_PUBLIC_FIREBASE_PROJECT_ID=NEXT_PUBLIC_FIREBASE_PROJECT_ID:latest,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:latest,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:latest,NEXT_PUBLIC_FIREBASE_APP_ID=NEXT_PUBLIC_FIREBASE_APP_ID:latest,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:latest,NEXT_PUBLIC_CANVAS_SNAPSHOT_URL=NEXT_PUBLIC_CANVAS_SNAPSHOT_URL:latest"

echo "✅ Frontend deployed."